### ISSUE TITLE
nmf.fit() error

### ISSUE THREAD

**Issue by smocz** [Specufex/specufex#19]
When attempting the geysers tutorial, there was an error in the specufex/nmf.py file (see attached screenshot). We resolved this by replacing line 83 in nmf.py with 

if np.any(np.min(X) < 0):

<img width="511" alt="geysers_error_screenshot" src="https://user-images.githubusercontent.com/107374133/224828197-ee59d6f6-ddaa-48a7-b29b-e6d07a264210.png">

**Comment by smocz** [comment]
New note, I found out this fix only works with batch_size = 1. I get the same error if batch_size != 1.

**Comment by ngroebner** [comment]
fixed in #22
